### ISSUE TITLE
Update the action

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/upload-release-assets#7]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mbehr1** [comment]
This should be resolved by changing:
https://github.com/sekwah41/upload-release-assets/blob/d1d5ea498ef078355322ed884029df152ba36389/package.json#L24
to 
@actions.core 1.10.0
or?

**Comment by sekwah41** [comment]
Will do :) didnt realise anyone else was using my action :P

**Comment by christian-weiss-df** [comment]
@v1.1.0 or its full hash still produces deprication warnings.

sekwah41/upload-release-assets@d33b61be358467363a2fd6532baabd54722875ed (version v1.1.1 of this fork) is working
